apiVersion: apps/v1
kind: Deployment

metadata:
  name: es-deployment
  labels:
    app: es-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-deployment
  template:
    metadata:
      labels:
        app: es-deployment
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.16.2
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xmx256m -Xms256m"
---
apiVersion: v1
kind: Service

metadata:
  name: elasticsearch

spec:
  type: ClusterIP
  selector:
    app: es-deployment

  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
   
