apiVersion: v1
kind: ConfigMap
metadata:
  name: shortify-config

data:
  redis_host: "redis"
  elastic_search_host: "elasticsearch"
  es_port: "9200"
  es_index: "redirect-log"
  ttl: "300000000"
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: redis-deployment
  labels:
    app: redis-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-deployment
  template:
    metadata:
      labels:
        app: redis-deployment
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service

metadata:
  name: redis

spec:
  type: ClusterIP
  selector:
    app: redis-deployment

  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
